import Head from 'next/head'

import LandingSection from '../components/LandingSection'
import HeadingSection from '../components/HeadingSection'
import Project from '../components/Project'

import jugo from './../public/jugo-project.png'
import tehno from './../public/tehno.png'
import ulnaris from './../public/ulnaris.png'
import audi from './../public/audi.png'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <LandingSection />
      <HeadingSection
        title={'work.'}
        paragraph={
          'Each client is unique and so is each project. While we have delivered many design projects, however, we need to honour the confidentiality of our clients. Here is quick glimpse of our portfolio.'
        }
      />

      <Project
        company={'Tehnoplast'}
        title={'Production and installation of ALU and PVC joinery'}
        tech={'web design development'}
        src={tehno}
      />

      <Project
        company={'Ulnaris Medical'}
        title={'Application for entering patients into the database'}
        tech={'web design development'}
        src={ulnaris}
        reverse
      />

      <Project
        company={'Jugometal'}
        title={'Tractors and agricultural machinery'}
        tech={'web design development'}
        src={jugo}
      />

      <Project
        company={'Audi & Tesla'}
        title={'Tesla inspired website design with Audi models'}
        tech={'web design development'}
        src={audi}
        reverse
      />

      <Footer />
    </div>
  )
}
